# reload config
bind=SUPER,r,spawn_shell,bash ~/.config/mango/scripts/config_check.sh
bind=SUPER,r,reload_config

# teminal and menu
bind=SUPER,x,spawn,ghostty
bind=SUPER,space,spawn,rofi -show drun
bind=SUPER,C,spawn,rofi -show calc -modi calc -no-show-match -no-sort

# exit super+m
# bind=SUPER,code:58,quit
bind=SUPER,m,quit
# killclient super+q
# bind=ALT,code:24,killclient,
bind=SUPER,q,killclient,

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER+SHIFT,Tab,focuslast
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
# Not sure what global does yet
# bind=SUPER,g,toggleglobal,
bind=SUPER,v,togglefloating,
bind=SUPER,f,togglefullscreen,
bind=SUPER+SHIFT,I,restore_minimized
bind=ALT,Tab,toggleoverview,0

# Swap Workspace
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# Move window to workspace
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

bind=Super,1,toggleview,1
bind=Super,2,toggleview,2
bind=Super,3,toggleview,3
bind=Super,4,toggleview,4
bind=Super,5,toggleview,5
bind=Super,6,toggleview,6
bind=Super,7,toggleview,7
bind=Super,8,toggleview,8
bind=Super,9,toggleview,9

# Mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Gesturebind
gesturebind=none,left,3,focusdir,left
gesturebind=none,right,3,focusdir,right
gesturebind=none,up,3,focusdir,up
gesturebind=none,down,3,focusdir,down
gesturebind=none,left,4,viewtoleft_have_client
gesturebind=none,right,4,viewtoright_have_client
gesturebind=none,up,4,toggleoverview,1
gesturebind=none,down,4,toggleoverview,1

# brightness and volume
bind=none,XF86AudioRaiseVolume,spawn,~/.config/mango/scripts/volume.sh up
bind=none,XF86AudioLowerVolume,spawn,~/.config/mango/scripts/volume.sh down
bind=none,XF86AudioMute,spawn,~/.config/mango/scripts/volume.sh mute
bind=none,XF86MonBrightnessUp,spawn,~/.config/mango/scripts/brightness.sh up
bind=none,XF86MonBrightnessDown,spawn,~/.config/mango/scripts/brightness.sh down

# Screenshots!
bind=none,PRINT,spawn,~/.config/mango/scripts/screenshot.sh
